name: use-trivy
on: [workflow_dispatch, push]
jobs:
  use-trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
  
      - name: Install dependencies
        run: npm ci

      - name: Use trivy
        uses: ./.github/actions/use-trivy